name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          sudo apt-get install -y pandoc
          mkdir -p dist
          sh generate.sh

